In [25]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_json('data.json')
df

link  \
0     https://www.isna.ir/news/1400072719610/۱۳۳۰۸-ا...   
1     https://www.isna.ir/news/1400071913382/سارا-شک...   
2     https://www.isna.ir/news/1400080100400/رعایت-پ...   
3     https://www.isna.ir/news/1400080503786/صدور-وی...   
4     https://www.isna.ir/news/1400081511093/کرونا-د...   
...                                                 ...   
1525  https://www.isna.ir/news/1400072921238/اعلام-م...   
1526  https://www.isna.ir/news/1400071711446/کنترل-ک...   
1527  https://www.isna.ir/news/1400081007411/آمار-مر...   
1528  https://www.isna.ir/news/1400081712891/فواید-ت...   
1529  https://www.isna.ir/news/1400072014067/دستاورد...   

                                                  title  \
0     ۱۳۳۰۸ ابتلای جدید کرونا در کشور / ۱۶۷ تن دیگر ...   
1                       «سارا شکری» شهید مدافع سلامت شد   
2     رعایت پروتکل ها در کرمان ضعیف است/ آمار پایین ...   
3                صدور ویزای توریستی ایران از سرگرفته شد   
4           کرونا در استان زنجان رنگ پاییزی به خود گرفت   
...                                                 ...   
1525  اعلام مجدد نگرانی علوم پزشکی اهواز از هرس نشدن...   
1526  کنترل کارت واکسیناسیون در رستوران‌ها و باشگاه‌ها    
1527  آمار مراجعین کرونایی جهت بستری در آذربایجان غر...   
1528                    فواید تزریق دوز سوم واکسن کرونا   
1529           دستاوردهای مقابله با کرونا در لبه پرتگاه   

                                                   body  \
0     به گزارش ایسنا و بنابر اعلام روابط عمومی وزارت...   
1     شهیده «سارا شکری» پرستار بیمارستان عشایر خرم‌آ...   
2     دکتر"حمیدرضا رشیدی نژاد" ظهر امروز اول آبان ما...   
3     به گزارش ایسنا، وزارت امور خارجه در فروردین‌ما...   
4     \n\n\nیکه‌تازی ویروس منحوس کرونا در ایران دو س...   
...                                                 ...   
1525  دکتر فرهاد ابول‌نژادیان در جمع خبرنگاران اظهار...   
1526  دکتر عبدالرضا جانگران‌نژاد در هشتاد و دومین جل...   
1527  \n\n\nجواد آقازاده در گفت و گو با ایسنا بابیان...   
1528  \n\n\nبه گزارش ایسنا، در یادداشتی در روزنامه ج...   
1529  به گزارش ایسنا، محمدحسین یزدی، رئیس مرکز تحقیق...   

                                                   tags publish_day  \
0                 [کرونا در ایران, همه_باهم_علیه_کرونا]     سه‌شنبه   
1     [استانی-اجتماعی, کرونا در ایران, شهید, دانشگاه...      دوشنبه   
2     [استانی-اجتماعی, کرونا در ایران, واکسیناسیون ک...        شنبه   
3     [گردشگري, ویزای ایران, رواديد, ویزای الکترونیک...    چهارشنبه   
4     [استانی-اجتماعی, زنجان, کرونا در ایران, واکسن ...        شنبه   
...                                                 ...         ...   
1525  [استانی-اجتماعی, اخبار اجتماعی - خوزستان, تنگی...     پنجشنبه   
1526  [استانی-اجتماعی, اخبار اجتماعی - خوزستان, کرون...        شنبه   
1527                   [استانی-اجتماعی, کرونا در ایران]      دوشنبه   
1528                      [واکسن کرونا, کرونا در ایران]      دوشنبه   
1529  [بازگشایی, کرونا در ایران, رئیس مرکز تحقیقات و...     سه‌شنبه   

          publish_datetime         category  
0      ۲۷ مهر ۱۴۰۰ / ۱۳:۵۲            سلامت  
1      ۱۹ مهر ۱۴۰۰ / ۲۱:۰۷           لرستان  
2      ۱ آبان ۱۴۰۰ / ۱۳:۰۸            کرمان  
3      ۵ آبان ۱۴۰۰ / ۱۵:۵۹  گردشگری و میراث  
4     ۱۵ آبان ۱۴۰۰ / ۱۲:۲۷            زنجان  
...                    ...              ...  
1525   ۲۹ مهر ۱۴۰۰ / ۱۳:۲۸          خوزستان  
1526   ۱۷ مهر ۱۴۰۰ / ۱۷:۴۴          خوزستان  
1527  ۱۰ آبان ۱۴۰۰ / ۱۴:۲۴   آذربایجان غربی  
1528  ۱۷ آبان ۱۴۰۰ / ۱۱:۲۸       رسانه دیگر  
1529   ۲۰ مهر ۱۴۰۰ / ۱۴:۳۱       رسانه دیگر  

[1530 rows x 7 columns]

In [3]:
with open('stopwords.txt') as stopwords_file:
    stopwords = stopwords_file.readlines()
    
stopwords = [line.replace('\n', '') for line in stopwords]


In [4]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)

In [5]:
import hazm
stemmer = hazm.Stemmer()

In [6]:
dataset  = pd.DataFrame(columns=('title_body', 'category'))
for index, row in df.iterrows():
    title_body = row['title'] + ' '+row['body']
    title_body_tokenized = hazm.word_tokenize(title_body)
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
    title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
    dataset.loc[index] = {
        'title_body':' '.join(title_body_tokenized_filtered_stemmed),
        'category':row['category'],
    }
    

In [7]:
list_tag=[]
for i in df.tags:
    list_tag.append( " ".join(i))
list_tag

['کرونا در ایران همه_باهم_علیه_کرونا',
 'استانی-اجتماعی کرونا در ایران شهید دانشگاه آزاد اسلامی لرستان',
 'استانی-اجتماعی کرونا در ایران واکسیناسیون کرونا استان کرمان پروتکل\u200cهای بهداشتی',
 'گردشگري ویزای ایران رواديد ویزای الکترونیکی کرونا در ایران واکسن کرونا',
 'استانی-اجتماعی زنجان کرونا در ایران واکسن کرونا',
 'گردشگري مقررات سفر گردشگران خارجی دستورالعمل حضور گردشگران خارجی کرونا در ایران',
 'کرونا در ایران همه_باهم_علیه_کرونا',
 'استانی-اجتماعی مهرداد بابایی کرونا در ایران واکسن کرونا',
 'استانی-اجتماعی دانشگاه علوم پزشکی سمنان کرونا در ایران منطقه سمنان',
 'استانی-اجتماعی کروناویروس همه_باهم_علیه_کرونا کرونا در ایران واکسن کرونا دانشگاه علوم پزشکی مشهد',
 'مقاله کرونا در ایران واکسن کرونا',
 'استانی-علمی و آموزشی کرونا در ایران کرونا در جهان همه_باهم_علیه_کرونا آنتی\u200cبادی کووید-19 واکسن کرونا',
 'استانی-اجتماعی کرونا در ایران واکسن کرونا',
 'آموزش حضوری دانشجویان دانشگاه ها وزير علوم کرونا در ایران',
 'آموزش حضوری دانشجویان دانشگاه تهران دانشگاه تهران واکسیناسینون دانشج

In [8]:

dataset.title_body = df.publish_day+" "+ list_tag +" "+ dataset.title_body
dataset

title_body         category
0     سه‌شنبه کرونا در ایران همه_باهم_علیه_کرونا ۱۳۳...            سلامت
1     دوشنبه استانی-اجتماعی کرونا در ایران شهید دانش...           لرستان
2     شنبه استانی-اجتماعی کرونا در ایران واکسیناسیون...            کرمان
3     چهارشنبه گردشگري ویزای ایران رواديد ویزای الکت...  گردشگری و میراث
4     شنبه استانی-اجتماعی زنجان کرونا در ایران واکسن...            زنجان
...                                                 ...              ...
1525  پنجشنبه استانی-اجتماعی اخبار اجتماعی - خوزستان...          خوزستان
1526  شنبه استانی-اجتماعی اخبار اجتماعی - خوزستان کر...          خوزستان
1527  دوشنبه استانی-اجتماعی کرونا در ایران آمار مراج...   آذربایجان غربی
1528  دوشنبه واکسن کرونا کرونا در ایران فواید تزریق ...       رسانه دیگر
1529  سه‌شنبه بازگشایی کرونا در ایران رئیس مرکز تحقی...       رسانه دیگر

[1530 rows x 2 columns]

In [9]:

sport =['فوتبال، فوتسال']
news= ['استانی','تهران','خوزستان','بوشهر','اصفهان','گزارش','خبر','رسانه','رسانه دیگر',
         'خراسان رضوی','فارس','آذربایجان شرقی',
        'مازندران','کرمان','البرز','گیلان','کهگیلویه و بویراحمد','آذربایجان غربی',
         'هرمزگان','مرکزی','یزد','کرمانشاه','قزوین',
         'سیستان و بلوچستان','همدان','ایلام','گلستان',
         'لرستان','زنجان','اردبیل','کردستان','قم',
         'سمنان','چهارمحال و بختیاری','خراسان شمالی','خراسان جنوبی'
        ]
learn =['آموزش','آموزش و پرورش','جهاد دانشگاهی','پژوهش','اینفوگرافیک','علم و فناوری جهان','علم و فناوری ایران']
political = ['دولت','مجلس','سیاست داخلی','سیاست خارجی']
cultural = ['تجسمی و موسیقی','سینما و تئاتر','صنفی، فرهنگی','گردشگری و میراث']
ho =['انتظامی','حقوقی و قضایی','حوادث، انتظامی']
list_ = [sport,news,learn,political,cultural,ho]
cat= ['ورزشی','استانی-اجتماعی','آموزش','سیاسی','فرهنگی و هنری','حقوقی انتظامی']

In [10]:
for i in np.unique(dataset.category):
    for j in range(0, len(list_)):
        if i in list_[j]:
        
            dataset= dataset.replace(i,cat[j])
print(np.unique(dataset.category))

['آموزش' 'استانی-اجتماعی' 'جامعه، شهری' 'حقوقی انتظامی' 'خانواده' 'سلامت'
 'سیاسی' 'فرهنگی و هنری' 'ورزشی']


In [11]:
dataset

title_body        category
0     سه‌شنبه کرونا در ایران همه_باهم_علیه_کرونا ۱۳۳...           سلامت
1     دوشنبه استانی-اجتماعی کرونا در ایران شهید دانش...  استانی-اجتماعی
2     شنبه استانی-اجتماعی کرونا در ایران واکسیناسیون...  استانی-اجتماعی
3     چهارشنبه گردشگري ویزای ایران رواديد ویزای الکت...   فرهنگی و هنری
4     شنبه استانی-اجتماعی زنجان کرونا در ایران واکسن...  استانی-اجتماعی
...                                                 ...             ...
1525  پنجشنبه استانی-اجتماعی اخبار اجتماعی - خوزستان...  استانی-اجتماعی
1526  شنبه استانی-اجتماعی اخبار اجتماعی - خوزستان کر...  استانی-اجتماعی
1527  دوشنبه استانی-اجتماعی کرونا در ایران آمار مراج...  استانی-اجتماعی
1528  دوشنبه واکسن کرونا کرونا در ایران فواید تزریق ...  استانی-اجتماعی
1529  سه‌شنبه بازگشایی کرونا در ایران رئیس مرکز تحقی...  استانی-اجتماعی

[1530 rows x 2 columns]

In [12]:
vectorizer = TfidfVectorizer()
vectorizer.fit(dataset.title_body)
X =vectorizer.transform(dataset.title_body)
le = LabelEncoder()

y= le.fit_transform(dataset.category)

In [13]:
np.shape(X)

(1530, 13854)

In [14]:
np.shape(y)

(1530,)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y)#,train_size=.20)

In [16]:
svmc = SVC()
svmc.fit(X_train,y_train)

SVC()

In [17]:
svmc.score(X_test,y_test)
y_pred = svmc.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.25      0.40        12
           1       0.86      0.99      0.92       275
           2       0.00      0.00      0.00         7
           3       0.25      0.33      0.29         3
           5       0.92      0.74      0.82        62
           6       1.00      0.12      0.22         8
           7       0.83      0.31      0.45        16

    accuracy                           0.86       383
   macro avg       0.69      0.39      0.44       383
weighted avg       0.85      0.86      0.83       383



/home/ali/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ali/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ali/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5)
neigh.fit(X_train, y_train)
y_pred = neigh.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.58      0.70        12
           1       0.90      0.96      0.93       275
           2       0.75      0.43      0.55         7
           3       0.25      0.33      0.29         3
           5       0.81      0.71      0.76        62
           6       1.00      0.38      0.55         8
           7       0.73      0.69      0.71        16

    accuracy                           0.87       383
   macro avg       0.76      0.58      0.64       383
weighted avg       0.87      0.87      0.87       383



In [27]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.41      0.58      0.48        12
           1       0.98      0.97      0.97       275
           2       0.40      0.29      0.33         7
           3       0.50      0.33      0.40         3
           4       0.00      0.00      0.00         0
           5       0.86      0.92      0.89        62
           6       0.62      0.62      0.62         8
           7       0.46      0.38      0.41        16

    accuracy                           0.90       383
   macro avg       0.53      0.51      0.51       383
weighted avg       0.90      0.90      0.90       383



/home/ali/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ali/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ali/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
print(confusion_matrix(y_test, y_pred))

[[  8   3   0   0   0   0   1]
 [  0 269   0   0   5   0   1]
 [  0   1   4   2   0   0   0]
 [  0   2   0   1   0   0   0]
 [  0  18   0   1  42   0   1]
 [  0   4   0   0   2   2   0]
 [  0   6   0   0   0   0  10]]


In [21]:
clf = GradientBoostingClassifier().fit(X_train, y_train)

In [22]:
# clf.score(X_test,y_test)
y_pred1 = clf.predict(X_test)
# clf.score(y_test,y_pred1)

In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.67      0.80        12
           1       0.89      0.98      0.93       275
           2       1.00      0.57      0.73         7
           3       0.25      0.33      0.29         3
           5       0.86      0.68      0.76        62
           6       1.00      0.25      0.40         8
           7       0.77      0.62      0.69        16

    accuracy                           0.88       383
   macro avg       0.82      0.59      0.66       383
weighted avg       0.88      0.88      0.87       383

